import { UserProvider } from '@auth0/nextjs-auth0/client';
import Nav from './nav';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Nav />
          {children}
        </body>
      </UserProvider>
    </html>
  )
}
